from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

from PyQt5.QtWidgets import QMessageBox
class ViewEmployees( object ):
    
    def ClearFields(self):
        self.EmpIDS.clear()
        self.EmpID.clear()
        self.EmpName.clear()
        self.EmpAddress.clear()
        self.EmpEmail.clear()
        self.EmpStatus.setCurrentText( "" )
        self.EmpGender.setCurrentText( "" )
        self.EmpSalary.setCurrentText( "" )
        self.EmpJob.setCurrentText( "" )
        self.EmpAge.clear()
        self.EmpPhone.clear()
    def loadingData(self):
        db = sqlite3.connect( "project.db" )
        result = db.execute( "select * from EmployeeInfo" )
        self.tableWidget.setRowCount( 0 )
        
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        db.close()
        
        self.ClearFields()
    
    def SearchClicked(self):
        
        ID = self.EmpIDS.text()
        db = sqlite3.connect("project.db")
        result = db.execute("select * from EmployeeInfo where ID="+ID)
        self.tableWidget.setRowCount( 0 )
        
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        
        list = [] 
        ViewName = db.execute("select * from EmployeeInfo where ID="+ID)
        for RowNum, RowDATA in enumerate( ViewName ):
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                list.append(ColumnData)
        
        self.EmpID.setText(str(list[0]))
        self.EmpName.setText(list[1])
        self.EmpAddress.setText(list[2])
        self.EmpEmail.setText(list[3])
        self.EmpPhone.setText( str( list[4] ) )
        self.EmpAge.setText( str( list[5] ) )
        self.EmpStatus.setCurrentText(list[6])
        self.EmpGender.setCurrentText(list[7])
        self.EmpJob.setCurrentText( list[8] )
        self.EmpSalary.setCurrentText(list[9])
        db.close()
    
    def DeleteClicked(self):
        
        ID = self.EmpIDS.text()
        db = sqlite3.connect( "project.db" )
        db.execute( "delete from EmployeeInfo where ID=" +ID)
        db.commit()
        message1 = QMessageBox()
        message1.setWindowTitle( "Successfull" )
        message1.setInformativeText( "Vous avez supprimé avec succès les informations de:  " + ID )
        message1.exec_()
        result = db.execute("select * from EmployeeInfo")
        self.tableWidget.setRowCount( 0 )
        
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )

        db.close()
        
        self.ClearFields()
    
    def UpdateData(self):
        
        ID = self.EmpID.text()
        Name = self.EmpName.text()
        Address= self.EmpAddress.text()
        Email = self.EmpEmail.text()
        Status = self.EmpStatus.currentText()
        Gender = self.EmpGender.currentText()
        Salary = self.EmpSalary.currentText()
        Job = self.EmpJob.currentText()
        Age = self.EmpAge.text()
        Phone = self.EmpPhone.text()
        db = sqlite3.connect("project.db")
        
        db.execute("update EmployeeInfo set ID=?, Name=?, Address=?, Email=?, Phone=?, Age=?, Status=?, Gender=?, Job=?, Salary=? where ID ="+"'"+ID+"'",
                   (ID, Name, Address, Email, Phone, Age, Status, Gender, Job, Salary))
        db.commit()
        message1 = QMessageBox()
        message1.setWindowTitle( "Successfull" )
        message1.setInformativeText( "Vous avez mis à jour avec succès les informations de   " + Name )
        x = message1.exec_()

        result = db.execute( "select * from EmployeeInfo where ID=" +ID)
        self.tableWidget.setRowCount( 0 )
        
        for RowNum, RowDATA in enumerate( result ):
            self.tableWidget.insertRow( RowNum )
            for ColumnNum, ColumnData in enumerate( RowDATA ):
                self.tableWidget.setItem( RowNum, ColumnNum, QtWidgets.QTableWidgetItem( str( ColumnData ) ) )
        db.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindowAdmin")
        MainWindow.resize(652, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(260, 20, 91, 31))
        self.SearchButton.setObjectName("SearchB")
        self.SearchButton.clicked.connect(self.SearchClicked)
        self.ViewEmp = QtWidgets.QPushButton(self.centralwidget)
        self.ViewEmp.setGeometry(QtCore.QRect(534, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ViewEmp.setFont(font)
        self.ViewEmp.setObjectName("ViewEmp")
        self.ViewEmp.clicked.connect(self.loadingData)
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(530, 490, 91, 31))
        self.UpdateButton.setObjectName("UpdateRecordB")
        self.UpdateButton.clicked.connect(self.UpdateData)
        self.EmpIDS = QtWidgets.QLineEdit( self.centralwidget )
        self.EmpIDS.setGeometry( QtCore.QRect( 100, 20, 141, 31 ) )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EmpIDS.setFont( font )
        self.EmpIDS.setObjectName( "EmpIDS" )
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 18, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(370, 20, 91, 31))
        self.DeleteButton.setObjectName("DeleteRecordB")
        self.DeleteButton.clicked.connect(self.DeleteClicked)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 651, 291))
        self.tableWidget.setStyleSheet("background-color: rgb(235, 235, 255);\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 370,150, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 370, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 410, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 491, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 410,120, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_2")
        self.EmpID = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpID.setGeometry(QtCore.QRect(120, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpID.setFont(font)
        self.EmpID.setObjectName("EmpID")
        self.EmpAge = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpAge.setGeometry(QtCore.QRect(510, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpAge.setFont(font)
        self.EmpAge.setObjectName("EmpAge")
        self.EmpEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpEmail.setGeometry(QtCore.QRect(120, 491, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpEmail.setFont(font)
        self.EmpEmail.setObjectName("EmpEmail")
        self.EmpAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpAddress.setGeometry(QtCore.QRect(120, 450, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpAddress.setFont(font)
        self.EmpAddress.setObjectName("EmpAddress")
        self.EmpStatus = QtWidgets.QComboBox(self.centralwidget)
        self.EmpStatus.setGeometry(QtCore.QRect(330, 370, 81, 31))
        self.EmpStatus.setObjectName("EmpStatus")
        self.EmpStatus.addItem("")
        self.EmpStatus.setItemText(0, "")
        self.EmpStatus.addItem("")
        self.EmpStatus.addItem("")
        self.EmpStatus.addItem("")
        self.EmpStatus.addItem("")
        self.EmpGender = QtWidgets.QComboBox(self.centralwidget)
        self.EmpGender.setGeometry(QtCore.QRect(330, 410, 81, 31))
        self.EmpGender.setObjectName("EmpGender")
        self.EmpGender.addItem("")
        self.EmpGender.setItemText(0, "")
        self.EmpGender.addItem("")
        self.EmpGender.addItem("")
        self.EmpGender.addItem("")
        self.EmpName = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpName.setGeometry(QtCore.QRect(120, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpName.setFont(font)
        self.EmpName.setObjectName("EmpName")
        self.EmpJob = QtWidgets.QComboBox(self.centralwidget)
        self.EmpJob.setGeometry(QtCore.QRect(330, 490, 121, 31))
        self.EmpJob.setObjectName("EmpJob")
        self.EmpJob.addItem("")
        self.EmpJob.setItemText(0, "")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpJob.addItem("")
        self.EmpSalary = QtWidgets.QComboBox(self.centralwidget)
        self.EmpSalary.setGeometry(QtCore.QRect(330, 450, 101, 31))
        self.EmpSalary.setObjectName("EmpSalary")
        self.EmpSalary.addItem("")
        self.EmpSalary.setItemText(0, "")
        self.EmpSalary.addItem("")
        self.EmpSalary.addItem("")
        self.EmpSalary.addItem("")
        self.EmpSalary.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 409, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_7")
        self.EmpPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.EmpPhone.setGeometry(QtCore.QRect(510, 410, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EmpPhone.setFont(font)
        self.EmpPhone.setObjectName("EmpPhone")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindowAdmin", "MainWindowAdmin"))
        self.SearchButton.setText(_translate("MainWindowAdmin", "Recherche"))
        self.ViewEmp.setText(_translate("MainWindowAdmin", "Les employés"))
        self.UpdateButton.setText(_translate("MainWindowAdmin", "Mise à jour"))
        self.label.setText(_translate("MainWindowAdmin", "ID:"))
        self.DeleteButton.setText(_translate("MainWindowAdmin", "Supprimer"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowAdmin", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowAdmin", "Nom et Prénom:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowAdmin", "Adresse"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowAdmin", "E-mail"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowAdmin", "Téléphone"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowAdmin", "Âge"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowAdmin", "État Civil"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindowAdmin", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindowAdmin", "Profession"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindowAdmin", "Salaire"))
        self.label_2.setText(_translate("MainWindowAdmin", "ID:"))
        self.label_3.setText(_translate("MainWindowAdmin", "État Civil:"))
        self.label_4.setText(_translate("MainWindowAdmin", "Gender:"))
        self.label_5.setText(_translate("MainWindowAdmin", "Age: "))
        self.label_6.setText(_translate("MainWindowAdmin", "Profession:"))
        self.label_7.setText(_translate("MainWindowAdmin", "E-mail:"))
        self.label_8.setText(_translate("MainWindowAdmin", "Adresse:"))
        self.label_9.setText(_translate("MainWindowAdmin", "Nom et Prénom:"))
        self.EmpStatus.setItemText(1, _translate("MainWindowAdmin", "Célibataire"))
        self.EmpStatus.setItemText(2, _translate("MainWindowAdmin", "Marié"))
        self.EmpStatus.setItemText(3, _translate("MainWindowAdmin", "Divorcé"))
        self.EmpStatus.setItemText(4, _translate("MainWindowAdmin", "Veuve"))
        self.EmpGender.setItemText(1, _translate("MainWindowAdmin", "Homme"))
        self.EmpGender.setItemText(2, _translate("MainWindowAdmin", "Femelle"))
        self.EmpJob.setItemText(1, _translate("MainWindowAdmin", "Généraliste"))
        self.EmpJob.setItemText(2, _translate("MainWindowAdmin", "Cardiologue"))
        self.EmpJob.setItemText(3, _translate("MainWindowAdmin", "Gastro-entérologue"))
        self.EmpJob.setItemText(4, _translate("MainWindowAdmin", "Neurologue"))
        self.EmpJob.setItemText(5, _translate("MainWindowAdmin", "Chirurgien"))
        self.EmpJob.setItemText(6, _translate("MainWindowAdmin", "Rhumatologue"))
        self.EmpJob.setItemText(7, _translate("MainWindowAdmin", "Allergologue"))
        self.EmpJob.setItemText(8, _translate("MainWindowAdmin", "Ophtalmologue"))
        self.EmpJob.setItemText(9, _translate("MainWindowAdmin", "Gynecologue"))
        self.EmpJob.setItemText(10, _translate("MainWindowAdmin", "Hématologue"))
        self.EmpJob.setItemText(11, _translate("MainWindowAdmin", "Dentiste"))
        self.EmpJob.setItemText(12, _translate("MainWindowAdmin", "Anesthésiste"))
        self.EmpJob.setItemText(13, _translate("MainWindowAdmin", "Pneumologue"))
        self.EmpJob.setItemText(14, _translate("MainWindowAdmin", "Psychiatre"))
        self.EmpJob.setItemText(15, _translate("MainWindowAdmin", "Radiologue"))
        self.EmpJob.setItemText(16, _translate("MainWindowAdmin", "Orthopediste"))
        self.EmpJob.setItemText(17, _translate("MainWindowAdmin", "Endocrinologue"))
        self.EmpJob.setItemText(18, _translate("MainWindowAdmin", "Toxicologue"))
        self.EmpJob.setItemText(19, _translate("MainWindowAdmin", "Autre"))
        self.EmpSalary.setItemText(1, _translate("MainWindowAdmin", "1000 - 6000 MAD"))  
        self.EmpSalary.setItemText(2, _translate("MainWindowAdmin", "6000 - 7000 MAD "))
        self.EmpSalary.setItemText(3, _translate("MainWindowAdmin", "7000 - 10000 MAD "))
        self.EmpSalary.setItemText(4, _translate("MainWindowAdmin", "+ 10000 MAD "))
        self.label_10.setText(_translate("MainWindowAdmin", "Salaire:"))
        self.label_11.setText(_translate("MainWindowAdmin", "Téléphone:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ViewEmployees()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
